package com.jianma.xtdm.model;
// Generated 2017-7-11 16:02:59 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "article", catalog = "xtdm")
public class Article implements java.io.Serializable {

	private Integer id;
	private int categoryId;
	private String title;
	private String abstractContent;
	private String label;
	private byte recommand;
	private String thumb;
	private String bgUrl;
	private Byte type;
	private String content;
	private Date createTime;

	public Article() {
	}

	public Article(int id, int categoryId, String title, String abstractContent, String label, byte recommand, String thumb,Date createTime){
		this.categoryId = categoryId;
		this.title = title;
		this.abstractContent = abstractContent;
		this.label = label;
		this.recommand = recommand;
		this.thumb = thumb;
		this.createTime = createTime;
		this.id = id;
	}
	
	public Article(int categoryId, byte recommand, String content) {
		this.categoryId = categoryId;
		this.recommand = recommand;
		this.content = content;
	}

	public Article(int id,int categoryId, String title, String abstractContent, String label, byte recommand, String thumb,
			String bgUrl, Date createTime) {
		this.id = id;
		this.categoryId = categoryId;
		this.title = title;
		this.abstractContent = abstractContent;
		this.label = label;
		this.recommand = recommand;
		this.thumb = thumb;
		this.bgUrl = bgUrl;
		this.createTime = createTime;
	}
	
	public Article(int id,int categoryId, String title, String abstractContent, String label, byte recommand, String thumb,
			String bgUrl, Byte type, String content, Date createTime) {
		this.id = id;
		this.categoryId = categoryId;
		this.title = title;
		this.abstractContent = abstractContent;
		this.label = label;
		this.recommand = recommand;
		this.thumb = thumb;
		this.bgUrl = bgUrl;
		this.type = type;
		this.content = content;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "categoryId", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "abstractContent")
	public String getAbstractContent() {
		return this.abstractContent;
	}

	public void setAbstractContent(String abstractContent) {
		this.abstractContent = abstractContent;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "recommand", nullable = false)
	public byte getRecommand() {
		return this.recommand;
	}

	public void setRecommand(byte recommand) {
		this.recommand = recommand;
	}

	@Column(name = "thumb", length = 100)
	public String getThumb() {
		return this.thumb;
	}

	public void setThumb(String thumb) {
		this.thumb = thumb;
	}

	@Column(name = "bgUrl", length = 100)
	public String getBgUrl() {
		return this.bgUrl;
	}

	public void setBgUrl(String bgUrl) {
		this.bgUrl = bgUrl;
	}

	@Column(name = "type")
	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
